# Generated by Django 5.0.7 on 2024-10-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("capitalminded", "0003_customuser_groups_customuser_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessregistration",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
