# Generated by Django 5.1.2 on 2024-10-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitalminded', '0003_alter_microloan_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microloan',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
