# Generated by Django 5.1.2 on 2024-10-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitalminded', '0004_alter_microloan_next_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microloan',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
