# Generated by Django 5.0.7 on 2024-10-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("capitalminded", "0004_businessregistration_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessregistration",
            name="business_plan",
            field=models.FileField(blank=True, null=True, upload_to="business_plans/"),
        ),
        migrations.AlterField(
            model_name="businessregistration",
            name="financial_statements",
            field=models.FileField(
                blank=True, null=True, upload_to="financial_statements/"
            ),
        ),
        migrations.AlterField(
            model_name="businessregistration",
            name="industry",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="businessregistration",
            name="legal_documents",
            field=models.FileField(blank=True, null=True, upload_to="legal_documents/"),
        ),
        migrations.AlterField(
            model_name="businessregistration",
            name="logo",
            field=models.ImageField(upload_to="logos/"),
        ),
        migrations.AlterField(
            model_name="businessregistration",
            name="management_profiles",
            field=models.FileField(
                blank=True, null=True, upload_to="management_profiles/"
            ),
        ),
        migrations.AlterField(
            model_name="businessregistration",
            name="ownership",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="businessregistration",
            name="tax_reg",
            field=models.CharField(max_length=255),
        ),
    ]
