# Generated by Django 5.1.2 on 2024-10-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitalminded', '0005_alter_microloan_remaining_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='interest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='principal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='microloan',
            name='interest_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='microloan',
            name='principal_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
