# Generated by Django 5.0.7 on 2024-10-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("capitalminded", "0005_alter_businessregistration_business_plan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessregistration",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
